apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis2
  name: redis2
spec:
  type: ClusterIP
  ports:
  - name: "redis2-service"
    port: 6379
    targetPort: 6379
  selector:
    app: redis2
  
