apiVersion: v1
kind: Service
metadata:
  labels:
    app: result2
  name: result2
spec:
  type: NodePort
  ports:
  - name: "result2-service"
    port: 8081
    targetPort: 8081
    nodePort: 31001
  selector:
    app: result2
