apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote2
  name: vote2
spec:
  type: NodePort
  ports:
  - name: "vote2-service"
    port: 8080
    targetPort: 8080
    nodePort: 32000
  selector:
    app: vote2
  
