apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker2
  name: worker2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker2
  template:
    metadata:
      labels:
        app: worker2
    spec:
      containers:
      - image: dockersamples/examplevotingapp_worker
        name: worker2
